### ISSUE TITLE
doubts about training

### ISSUE THREAD

**Issue by cyberpunk207777** [z-x-yang/NS-Outpainting#10]
sorry to bother you again with this, my query is when you train the model on the images it should be done using unsupervised learning as there are no labels right? so what clustering algorithm was used while training this model?

**Comment by z-x-yang** [comment]
I split each image into two half images horizontally. Given the left one, our model needed to predict the right one in the training process—no unsupervised learning.

**Comment by cyberpunk207777** [comment]
> 
> 
> I split each image into two half images horizontally. Given the left one, our model needed to predict the right one in the training process—no unsupervised learning.

whoa i was thinking wrong this whole time, wait if the half image is given how can the model generate the fake image which is different than the original right half of the image? does it have something to do with activation function and loss function?

**Comment by z-x-yang** [comment]
We use a recurrent neural sub-network to infer the feature of the right half. And we use a GAN loss to improve the quality of right half predictions.
