### ISSUE TITLE
Bug in testing loop?

### ISSUE THREAD

**Issue by DeepLearner314** [z-x-yang/NS-Outpainting#12]
Hi, 
first of all congrats on the very interesting paper and code!

In train_model.py, line 304, the model is supposed to be run on the test images, as far as I understand. However, it is applied to the variable 'images', which actually come from the training set, and are defined further above in line 287. Shouldn't 'images' in line 304 be replaced by 'test_oris'?

**Comment by z-x-yang** [comment]
Thanks!

You're right. I will fix this bug.
