### ISSUE TITLE
how do I get output for custom input

### ISSUE THREAD

**Issue by lightyagami0279** [z-x-yang/NS-Outpainting#13]
With the help of "dataset/builddataset.py" I have generated  trainset.tfr and testflow.tfr for ori1.jpg and pasted in tf_dataset_new but when I run it results are empty!

please help

**Comment by z-x-yang** [comment]
What's the meaning of "for ori1.jpg"? Only one image was used for generating datasets?

**Comment by lightyagami0279** [comment]
> What's the meaning of "for ori1.jpg"? Only one image was used for generating datasets?

No, I used 20 images .
I just used name ori for better understanding

**Comment by z-x-yang** [comment]
OK.

So these images are in the test set. The script will split 1,000 images for testing, while the rest images for training.

**Comment by lightyagami0279** [comment]
How do you I reduce the number of images for testing!

**Comment by z-x-yang** [comment]
It's easy, check the [code](https://github.com/z-x-yang/NS-Outpainting/blob/4e07a72bad0f84053025e129bac16d5620374f7b/dataset/build_dataset.py#L26).

**Comment by lightyagami0279** [comment]
Thank you very much.

Really appreciate it, may I put this in school project?

**Comment by z-x-yang** [comment]
Sure.
