### ISSUE TITLE
about the tfr file format

### ISSUE THREAD

**Issue by Atomiciaz** [z-x-yang/NS-Outpainting#8]
Nice work btw
i got like 2 questions

1) how did you convert your data set to .tfr format? does it have to be .tfr or even raw images work?

2) while running the pretrained model why do we have to specify even 'training data set' path inside parser.add_argument again in eval_model.py? Isn't it trained already so we can just specify the testing data set path?

**Comment by z-x-yang** [comment]
1. Please refer to this [example](https://github.com/z-x-yang/NS-Outpainting/blob/master/dataset/build_dataset.py) for converting your data to TFRecord. TFRecord format leads to faster data loading. And I don't have a code using raw images. Sorry.

2. Hmmm. The model will not be trained again during evaluation. I just forgot to remove the code about 'training data set'...

**Comment by Atomiciaz** [comment]
Alright man ty for the fast reply, much appreciated.

**Comment by z-x-yang** [comment]
Sure thing.
