### ISSUE TITLE
unable to get results for testing with other images

### ISSUE THREAD

**Issue by cyberpunk207777** [z-x-yang/NS-Outpainting#9]
so, i ran eval_model.py on your pre trained model, it works good with your test data set but when i take images from other data sets and convert it into .tfr format and give it as testset to the pre trained model then im not getting results for the images i gave as testset but im even getting results of the images which aren't even present in the test data set so please tell me what changes should i make to get the desired result i want?

**Comment by z-x-yang** [comment]
I'm not sure what your images like, but I guess that the data distribution of your images is not similar to our dataset, thus the pre-trained model collapsed.

**Comment by cyberpunk207777** [comment]
> 
> 
> I'm not sure what your images like, but I guess that the data distribution of your images is not similar to our dataset, thus the pre-trained model collapsed.

my images were of natural sceneries too and yes my data distribution was different i only used like 50 images for testing so will it work fine if i use the same number of images you used while distributing it for testing and training sets?

**Comment by z-x-yang** [comment]
Sure. Fine-tuning the model on your data should improve the results. And more images in your training set, better the results.

**Comment by cyberpunk207777** [comment]
And last two doubts, if i wanna train my own model  can i give the data set which has images of any size or the images should be of any particular dimensions? and what should i do to checkpoint a newly trained model like you did to your pretrained model?

**Comment by z-x-yang** [comment]
This [script](https://github.com/z-x-yang/NS-Outpainting/blob/master/dataset/build_dataset.py) will reshape training images to a fixed scale, and the input size of NS-Outpainting is fixed to 128*128 in our code. You can try to modify the input size to a larger size, but you have to first modify the hyper-parameters of the sequence module in NS-Outpainting.

Besides, the training code will save checkpoints automatically.
